version: 2.1

.container_executor: &container_executor
  docker:
    - image: cimg/base:2022.06

.directory: &directory
  working_directory: ~/workspace

jobs:
  checkout-code:
    <<: *container_executor
    <<: *directory
    steps:
      - checkout
      - persist_to_workspace:
          root: ~/
          paths:
            - workspace

  build-image:
    <<: *container_executor
    <<: *directory
    steps:
      - setup_remote_docker:
         version: 20.10.14
      - attach_workspace:
          at: ~/
      - run: 
          name: docker_build
          command: |
            docker build -t kraaarpit/docker-react -f Dockerfile.dev .
            mkdir -p ~/workspace/docker-cache
            docker save -o ~/workspace/docker-cache/built-image.tar kraaarpit/docker-react
      - persist_to_workspace:
          root: ~/
          paths:
            - workspace
           

  test:
    <<: *container_executor
    <<: *directory
    steps:
      - setup_remote_docker:
         version: 20.10.14
      - attach_workspace:
          at: ~/
      - run: 
         name: docker_test
         command: |
            ls
            docker load -i ~/workspace/docker-cache/built-image.tar
            docker run -e CI=true kraaarpit/docker-react npm run test
  
  deploy:
    <<: *container_executor
    <<: *directory
    steps:
      - setup_remote_docker:
         version: 20.10.14
      - attach_workspace:
          at: ~/
      - run: 
         name: Installing Deployemnt dependencies
         command: |
            sudo apt-get -y -qq update
            sudo apt-get install python-pip python-dev build-essential
            sudo pip install --upgrade setuptools
            sudo pip install awsebcli --upgrade
      - run: 
         name: Deploying
         command: |
            eb deploy Dockerreact-env



workflows:
  build_and_test:
    jobs:
      - checkout-code
      - build-image:
          requires:
           - checkout-code
      - test:
          requires:
            - build-image
      - deploy:
          context: aws
          requires:
            - test
          filters:
            branches:
              only:
                - master
      
