version: 2.1

.container_executor: &container_executor
  docker:
    - image: cimg/base:2022.06

.directory: &directory
  working_directory: ~/workspace

jobs:
  checkout-code:
    <<: *container_executor
    <<: *directory
    steps:
      - checkout
      - persist_to_workspace:
          root: ~/
          paths:
            - workspace


workflows:
  build_and_test:
    jobs:
      - checkout-code
