version: 2.1

.container_executor: &container_executor
  docker:
    - image: cimg/base:2022.06

.directory: &directory
  working_directory: ~/workspace

jobs:
  checkout-code:
    <<: *container_executor
    <<: *directory
    steps:
      - checkout
      - persist_to_workspace:
          root: ~/
          paths:
            - workspace

  build-image:
    <<: *container_executor
    <<: *directory
    steps:
      - setup_remote_docker:
         version: 20.10.14
      - attach_workspace:
          at: ~/
      - run: 
         name: docker_build
         command: |
           docker build -t kraaarpit/docker-react -f Dockerfile.dev .



workflows:
  build_and_test:
    jobs:
      - checkout-code
      - build-image:
          requires:
           - checkout-code
