version: 2.1

jobs:
  build:
    working_directory: ~/app
    docker:
      - image: cimg/base:2022.06
    steps:
      - checkout
      - setup_remote_docker:
          version: 20.10.14
      - run: |
         docker build -t kraaarpit/docker-react -f Dockerfile.dev .
         docker run -e CI=true kraaarpit/docker-react npm run test
  test:
    working_directory: ~/app
    docker:
      - image: cimg/base:2022.06
    steps:
      - checkout
      - setup_remote_docker:
          version: 20.10.14
      - run:  docker run -e CI=true kraaarpit/docker-react npm run test

workflows:
  build_and_test:
    jobs:
      - build