version: 2.1

.container_executor: &container_executor
  docker:
    iamge: cimg/base:2022.06

.directory: &directory
  working_directory: ~/app

jobs:
  checkout-code:
    <<: *directory
    <<: *container_executor
    steps:
      - checkout

workflows:
  build_and_test:
    jobs:
      - checkout-code
